site_name: ISSW
site_description: ISSW Project Documentation
site_url: https://machtlp.github.io/Documentation_ISSW/

theme:
  name: mkdocs
  navigation_depth: 4

markdown_extensions:
  - toc:
      toc_depth: 4

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/image-lightbox.js
  - javascripts/finder-links.js
  - javascripts/mermaid-init.js
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

hooks:
  - hooks/private_include.py
  - hooks/daily_updates.py
  - hooks/todos.py
  - hooks/changelog.py

nav:
  - I. Home: index.md
  - II. Spatial Config: spatial-config.md
  - III. HRDPS: hrdps.md
  - IV. Info Ex: info-ex.md
  - V. Avapro Point Location: avapro/index.md
  - VI. SNOWPACK: snowpack.md
  - VII. AvaPro v1: avapro/v1.md
  - VIII. AvaPro v2: avapro/v2.md
  - IX. Status Update Aug 6: status-update-aug-6.md
  - X. Figures Plan: paper-figures-plan.md
  - XI. Plots for Paper Config: plots-for-paper-config.md
