site_name: ISSW
site_description: ISSW Project Documentation
site_url: https://machtlp.github.io/Documentation_ISSW/

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/image-lightbox.js
  - javascripts/mermaid-init.js

hooks:
  - hooks/private_include.py
  - hooks/todos.py
  - hooks/changelog.py

nav:
  - Home: index.md
  - Avapro Point Location: avapro/index.md
  - Spatial Config: spatial-config.md
  - HRDPS: hrdps.md
  - Info Ex: info-ex.md
